client_config_backend: settings
client_config:
  client_id: 620005863534-lua6h052h3bk53j5brtkfq1h15vh7ukt.apps.googleusercontent.com
  client_secret: VrwwlNrKVu6kC9A_oikn6766

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install